v = input('Введите число от 1 до 10: ')
print(int(v)+10)
name = input('Введите ваше имя: ')
print(f'Привет, {name}! Как дела?' )
a=float('1')
print(a )
val = '2.5'
print(val)
c=bool(1)
print(c)
v=bool(' ')
print(v)
l=bool(0)
print(l)
